name: Test Default Env Workflow

on:
  release:
    types:
      - published

  push:
    paths: 
      - action.*
    branches:
      - master

jobs:
  Run Test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
