name: Test Default Env Action

on:
  release:
    types:
      - published

  push:
    branches:
      - master

jobs:
  run-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
