name: Test Default Env Action

# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#referencing-actions-in-your-workflow

on:
  release:
    types:
      - published

  push:
    branches:
      - 'release/v*'

jobs:
  run-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
    - name: 'Show the env'
      run: echo 'Check the environment for this step'
