name: Test Default Env Workflow

on:
  release:
    types:
      - published

  push:
    paths: 
      - action.*
      - '.github/workflows/test.yml'
    branches:
      - master

jobs:
  run-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
